#!/usr/bin/env bash
set -euo pipefail
BUILD_DIR="${BUILD_DIR:-build}"
BUILD_TYPE="${BUILD_TYPE:-Release}"
ENABLE_TORCH="${ENABLE_TORCH:-ON}"
ENABLE_CUDA="${ENABLE_CUDA:-OFF}"
cmake -S . -B "${BUILD_DIR}"   -DCMAKE_BUILD_TYPE="${BUILD_TYPE}"   -DGPT2CPP_ENABLE_TORCH="${ENABLE_TORCH}"   -DGPT2CPP_ENABLE_CUDA="${ENABLE_CUDA}"   ${CMAKE_PREFIX_PATH:+-DCMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}"}
cmake --build "${BUILD_DIR}" -j
